### ISSUE TITLE
Epic) 관리자 페이지 기본 기능

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#46]
> 현재 관리자 페이지 디자인이 되어있지 않으므로 `권한` Task만 구현합니다.

- [ ] 권한
    - [ ] 더미 API 제작후 관리자 권한이 있는 경우만 다음 기능이 가능하도록 만듬.
---
- [ ] 공지사항 전송
    - [ ] 전체, 번역가 선택 가능
- [ ] 액션 로그
    - [ ] 로그에 있어야할 정보
        - [ ] IP
        - [ ] 사용자
        - [ ] 발생일
        - [ ] 액션의 종류
        - [ ] 액션이 일어난 링크 (좋아요한 만화 링크 등)
    - [ ] 로그 검색 기능
        - 모든 액션에는 로그가 기록됨.
        - [ ] 유저별 로그
        - [ ] 액션별 로그
            - [ ] 회원가입
            - [ ] 로그인
            - [ ] 태그 등록
            - [ ] 요청 등록/수정/삭제
            - [ ] 만화 등록/수정/삭제
            - [ ] 좋아요
            - [ ] 신고

## references
[팬픽시브 기능 정의서](http://simp.ly/p/PXD7hS)
[디자인 기획서](https://www.figma.com/file/02ZyXsy0r0nxq9PKa7khtN/fanfixiv?node-id=120%3A1681)

**Comment by JaehaSS** [comment]
로그 생성 부분들은 다른 서버에서 다 만드실 생각이신가요?

**Comment by Roharui** [comment]
제 설계대로라면 로그를 생성하는 API가 관리자서버에 있고 다른 서버가 특정 액션을 취할때 마다 그 API에 요청을 넣는 식으로 진행할 예정입니다.
