### ISSUE TITLE
컨텐츠 카드

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#54]
**Tasks**

- [ ]  태그 표시 기능
    1. 선호(사용자가 저장한) 태그
    2. 많이 사용된 태그 일수록 우선순위가 높음
    3. 완전 일치한 검색 태그
        → 검색 태그와 일치하는 태그의 노출 우선순위를 낮춘다.
        - [ ]  닫힘 상태에서 최대 표시 태그는 2~3개
        - [ ]  태그 길이에 따라 컨텐츠 카드가 늘어나면 안됌.
- [ ]  제목 표시 기능 (BOLD하고 크기가 약간 큼)
- [ ]  작가 표시 기능
- [ ]  페이지 수 표시 (아이콘 옆에 숫자)  (페이지가 하나일 경우 표시하지 않아도 됨.)
- [ ]  썸네일 표시 기능
- [ ]  좋아요
    - [ ]  좋아요 상태일때 하트가 검은색으로 표시됨
    - [ ]  검은색인 하트를 클릭시 좋아요 취소
- [ ]  *조회수 표시 (현재는 진행하지 않음.)*
- [ ]  컨텐츠 카드 클릭시 해당 만화 뷰어 열기
- [ ]  수정/삭제/신고
    - [ ]  더보기란 클릭시 수정/삭제/신고 선택란 띄움
    - [ ]  수정/삭제는 해당 만화의 번역가를 제외하고는 보이지 않음
    - [ ]  삭제시 삭제 확인 알림창 띄움
- [ ]  상세 보기/닫기 기능
    - [ ]  등록일 표시
    - [ ]  열림 상태에서 모든 태그 카테고리 별로 표시
    - [ ]  ~~선호 태그 우선표시~~

**레퍼런스**
- https://www.notion.so/a1d431ee708647449b63ca0fe4821b2f
