### ISSUE TITLE
만화 뷰어

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#55]
**만화 뷰어**

> 만화 뷰어는 페이지. 모달이 아님.

- [ ]  시리즈 목록 표시
    - [ ]  시리즈가 아닐 경우 표시하지 않음
- [ ]  이미지 표시 (가로 사이즈에 맞게)
- [ ]  제목 표시
- [ ]  번역가 표시
    - ~~클릭시 #프로필 페이지로 이동~~ (개발 예정)
- [ ]  등록일 표시
- [ ]  원작자 표시
    - 클릭시 원작자 검색 결과로 이동
- [ ]  번역후기 표시
- [ ]  출처 표시 (상단 또는 하단에 링크 표시)
    - [ ]  출처는 원작자, 번역가 둘다 표시하며 번역가 출처는 없을 경우 표시하지 않음.
- [ ]  ~~신고 기능~~ (다른 EPIC에서 처리)
- [ ]  수정/삭제 기능 (업로드한 번역가만 수정/삭제 가능)
    - 실제 수정 기능은 #57 에서 처리합니다. 
    - 다음 기능은 해당 유저가 업로더인지 아닌지 여부를 알고 화면에 표시하는 기능입니다.
