### ISSUE TITLE
검색 기능

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#60]
**Tasks**

- [ ]  검색란
    - [ ]  태그 자동완성 기능
        - 현재 검색한 내용과 자동완성 기능의 문구가 겹칠 경우 겹친 문구에 특정 색깔을 입힘.
    - [ ]  내용이 없을 경우 `검색 결과가 없습니다.` 텍스트 출력
    - [ ]  검색에 대한 결과물의 정렬은 등록일자 기준 (최신순).
        - 후일 정렬 태그 추가시 달라져야함.
- [ ]  **검색 기능**
    - [ ]  ~~일반 검색~~
        - [ ]  ~~일반 검색의 경우 한번의 검색으로 제목, 태그, 원작자를 전부 검색함.~~
        - [ ]  ~~일반 검색 이후 상단, 혹은 좌측에 태그 목록(검색결과에서 가장 많은 결과를 가진 태그 별로 정렬)을 표시하고 그 태그를 선택시 그 선택된 태그 목록을 보여줌.~~
    - [x]  태그 검색
        - [x]  태그를 검색함, 중복 태그 입력 가능
        -  엑스트라 태그 기능
            - [x] 인기 태그
            - [x] 좋아요 태그
    - [ ]  ~~검색 전환~~
        - [ ]  ~~#을 입력했을때 태그 검색으로 바로 이동~~
        - [ ]  ~~#버튼을 클릭했을때 태그 검색으로 전환~~
