### ISSUE TITLE
태그 요청

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#61]
**Tasks**

- [ ]  종류 선택
    - **원작자** (원작자의 태그 요청의 경우 로직이 다름으로 주의할것.)
    - 시리즈
    - 캐릭터
- [ ]  원작자 태그 요청시 원작자 링크 입력
    - [ ]  랑크에서 `search` 생략 (location.search를 의미함.)
    - [ ]  링크 복수 입력 가능
        - [ ]  같은 사이트일 경우 입력 불가
    - [ ]  중복확인
        - 기존에 있던 원작자 입력과 중복되면 입력되지 않음.
