### ISSUE TITLE
알림

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv_old#66]
**Tasks**

- [ ]  공지사항, 개인 알림 두가지 알림이 존재
- [ ]  공지사항은 알림 삭제 불가
- [ ]  개인 알림은 삭제 가능
